apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch-name
      default: main
    - name: image-name
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)

    - name: npm-install
      taskRef:
        name: npm
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: test
      taskRef:
        name: jasmine
      runAfter:
        - npm-install
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - test
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
